### ISSUE TITLE
BubbleShowcase cannot exceed highlighted widget's dimensions

### ISSUE THREAD

**Issue by Termtime** [Skyost/BubbleShowcase#16]
**Describe the bug**
If you set a RelativeBubbleSlide to be on a horizontal axis (`AxisDirection.right` or `AxisDirection.left`) the BubbleShowcase widget will at maximum be of the height of the widget and cannot exceed it.
If you set it to a vertical axis (`AxisDirection.up` or `AxisDirection.down`) the same happens but with the width of the RelativeBubbleSlide.

**To Reproduce**
1. In a Scaffold, create a small widget, for example an IconButton
2. Add a RelativeBubbleSlide that focuses on the key of the IconButton, the structure of the BubbleSlides follows the structure of the `BubbleSlide _firstSlide` in the `example.dart` file of this package.
4. Set the RelativeBubbleSlide direction to be a horizontal axis.
5. See how the container overflows from the text not being able to fit in the small height of the IconButton
6. Set the RelativeBubbleSlide direction to be a vertical axis.
7. See how the container overflows vertically from the text not being able to fit in the small width of the IconButton

**Expected behavior**
You should be able to go beyond the width/height of the widget you are highlighting.

**Screenshots**
![image](https://user-images.githubusercontent.com/49447170/133863831-fbd28938-cd21-49c9-a4dc-564e8d4c68aa.png)
![image](https://user-images.githubusercontent.com/49447170/133863916-8af2af02-d283-4b9b-8596-ddeb4457ee44.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android API 29
 - Flutter version: 2.2.3
 - bubble_showcase version: ^1.0.0

**Comment by Termtime** [comment]
I think #11 is related and might solve this issue

**Comment by janhaa** [comment]
@Termtime thank you for working on a fix!

I figured out that using OverflowBox is a temporary workaround solution for this issue, e.g.:

```dart
RelativeBubbleSlide(
  widgetKey: widgetToHighlightKey,
  child: RelativeBubbleSlideChild(
    direction: AxisDirection.up,
    widget: OverflowBox(maxWidth: 300, alignment: Alignment.centerLeft, child: Padding(
      padding: const EdgeInsets.only(top: 8),
      child: SpeechBubble(
        nipLocation: NipLocation.BOTTOM_LEFT,
        color: Colors.blue,
        child: Padding(
          padding: const EdgeInsets.all(10),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'That\'s cool !',
              ),
              Text(
                'This is my brand new title !',
              ),
            ],
          ),
        ),
      )),
    ),
  ),
```
