### ISSUE TITLE
Have the SpeechBubble display above the highlighted area

### ISSUE THREAD

**Issue by lunaticcoding** [Skyost/BubbleShowcase#2]
**Is your feature request related to a problem? Please describe.**
I need the Bubble to be displayed above the widget I want to highlight. Changing the direction property in the RelativeBubbleSlideChild should place it above right? :S But it does not. Otherwise, I simply used the code from the example. 

**Describe the solution you'd like**
A way to put the SpeechBubble above the widget. 

**Describe alternatives you've considered**
Using another plugin, but that one has other issues...

**Additional context**

**Comment by Skyost** [comment]
You could use something like this :

```dart
  RelativeBubbleSlide(
    widgetKey: widgetKey,
    child: RelativeBubbleSlideChild(
      direction: AxisDirection.up,
      widget: Padding(
        padding: EdgeInsets.only(bottom: 2),
        child: SpeechBubble(
          nipLocation: NipLocation.BOTTOM,
          color: Colors.blue,
          child: Padding(
            padding: EdgeInsets.all(10),
            child: Text('Yo !'),
          ),
        ),
      ),
    ),
  );
```

**Comment by lunaticcoding** [comment]
@Skyost That is pretty much what I used. Did not work for me.

**Comment by Skyost** [comment]
Fixed :wink:
