### ISSUE TITLE
RangeError when setting doNotReopenOnClose to true 

### ISSUE THREAD

**Issue by danielmarek** [Skyost/BubbleShowcase#3]
**Describe the bug**
I set up a few bubbles and showcases, and when I (later on) set doNotReopenOnClose to true, I get the following error:
RangeError (index): Invalid value: Not in range 0..1, inclusive: -1
This is at:
_BubbleShowcaseState._createCurrentSlideEntry.<anonymous closure> (package:bubble_showcase/src/showcase.dart:129:50)

**To Reproduce**
1) Create some bubbles and showcases
2) Enable doNotReopenOnClose

**Expected behavior**
No exception.

**Smartphone (please complete the following information):**
Nexus 5X API R Emulator on MacOS

**Comment by danielmarek** [comment]
Thanks! I can confirm this works fine for me now at 0.2.0+3

**Comment by Skyost** [comment]
Good :Wink:
